language: php

php:
    - 5.5
    - 5.6

before_script: phpenv config-add myconfig.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - chmod 777 app/bootstrap.php.cache  

script:
  - phpunit -c app/

notifications:
  email:
    -  lawson_richard@hotmail.com 
