php:
    - 5.5
    - 5.6

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit -c app

notifications:
  email:
    -  lawson_richard@hotmail.com 
