# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    game_socket_host: tcp://127.0.0.1
    game_socket_port: 8080

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    socket_pinger:
        class: AppBundle\Socket\SocketPinger
        arguments: ["%game_socket_host%", "%game_socket_port%"]     
    name_is_not_in_use_validator:
        class: AppBundle\Validator\Constraints\NameIsNotInUseValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: name_is_not_in_use
    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    app.profile_edit:
        class: AppBundle\EventListener\ProfileListener
        arguments: [ @router, @session ]
        tags:
            - { name: kernel.event_subscriber }
